### ISSUE TITLE
New subjects - what do you need to prep?

### ISSUE THREAD

**Issue by willettk** [murraycu/android-galaxyzoo#23]
Hi @murraycu - we have two new sets of subjects that should be put into Galaxy Zoo by next week. Both will have new survey names, but will use existing workflows. Can you tell me what you need in order for the app to be compatible with these new subjects?

**Comment by murraycu** [comment]
Ideally, I would see the changes to the GalaxyZoo web UI in a git branch:
https://github.com/zooniverse/Galaxy-Zoo
Then I could also check them for errors that will affect the web UI too.

You should really want to have these changes in a git branch before you push them to git master and deploy them.

**Comment by murraycu** [comment]
The decals_illustris tree for the app is ready to merge to master and deploy whenever these surveys go live on the website.
