### ISSUE TITLE
App is serving inactive subjects?

### ISSUE THREAD

**Issue by vrooje** [murraycu/android-galaxyzoo#25]
Looks like one of the volunteers is getting SDSS images via the Android app, even though SDSS is deactivated (we're only showing DECaLS and Illustris right now)...

http://talk.galaxyzoo.org/#/subjects/AGZ0004bz1

**Comment by hobeika** [comment]
Found only in 1.52.
Upgrading to 1.53 fixes the problem.

**Comment by murraycu** [comment]
Yes, that is normal. New surveys require new app releases. The server doesn't provide everything that would be needed to just download new questions for a new survey.

**Comment by vrooje** [comment]
Great, the volunteer confirms this fixed it. Sorry for the trouble!
